# Jekyll configuration

name: Leo Adamek
description: I write code and make stuff

# Url is currently only used only for the RSS feed in feed.xml
# nope, its used all over the site and makes things break :(
# url: https://leo.adamek.me
url: http://leo.adamek.me

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl:

social:
  github: LeoAdamek
  twitter: LeoAdamek
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blanc to ignore or put true to use
yandex_metrika:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
#disqus: LeoAdamek
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - "no_intra_emphasis"
    - "fenced_code_blocks"
    - "autolink"
    - "tables"
    - "with_toc_data"

exclude:
  - 'README.md'
  - 'LICENSE'

gems:
  - jekyll-paginate
